APPLICATION = sensor_temperature

BOARD ?= iotlab-m3

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ztimer_msec
USEMODULE += lps331ap

RIOTBASE ?= ../../../external/RIOT

include $(RIOTBASE)/Makefile.include
