# Stopper script generated by 
iotlab-experiment wait --timeout 30 --cancel-on-timeout -i 384386 --state Running
iotlab-experiment stop -i 384386
iotlab-experiment wait --timeout 30 --cancel-on-timeout -i 384385 --state Running
iotlab-experiment stop -i 384385
