version = 0.1
[default.deploy.parameters]
stack_name = "iot-app"
resolve_s3 = true
s3_prefix = "iot-app"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
