AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  IOTLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.8
      Role: !Sub "arn:aws:iam::293814872100:role/service-role/iotsqslambda"
      FunctionName: !Sub "IOTLambda"

  MySQSEvent:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      EventSourceArn: "arn:aws:sqs:eu-north-1:293814872100:iot-queue"
      FunctionName: !GetAtt IOTLambda.Arn